const data = [
  {
    id: 1,
    layer: 1,
    originKey: "apply_id",
    originValue: "1000002662709",
    tableType: 0,
  },
  {
    id: 2,
    layer: 1,
    originKey: "OBJECT_FIELD_decision_details",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 3,
    layer: 2,
    originKey: "OBJECT_FIELD_apply_info",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 4,
    layer: 3,
    originKey: "name",
    originValue: "杜永胜",
    tableType: 0,
  },
  {
    id: 5,
    layer: 3,
    originKey: "mobile",
    originValue: "15565221126",
    tableType: 0,
  },
  {
    id: 6,
    layer: 3,
    originKey: "idNumber",
    originValue: "410728199105133056",
    tableType: 0,
  },
  {
    id: 7,
    layer: 2,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 8,
    layer: 2,
    originKey: "avoidable_data_source_warning",
    originValue: "false",
    tableType: 0,
  },
  {
    id: 9,
    layer: 2,
    originKey: "ARRAY_FIELD_avoidable_rule_sets",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 10,
    layer: 2,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 11,
    layer: 2,
    originKey: "OBJECT_FIELD_base_infos",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 12,
    layer: 3,
    originKey: "app_name",
    originValue: "yxh_prod",
    tableType: 0,
  },
  {
    id: 13,
    layer: 3,
    originKey: "biz_id",
    originValue: "28",
    tableType: 0,
  },
  {
    id: 14,
    layer: 3,
    originKey: "created_at",
    originValue: "2021-01-02 00:00:09",
    tableType: 0,
  },
  {
    id: 15,
    layer: 3,
    originKey: "execution_machine_ip",
    originValue: "66.66.1.66",
    tableType: 0,
  },
  {
    id: 16,
    layer: 3,
    originKey: "release_type",
    originValue: "online",
    tableType: 0,
  },
  {
    id: 17,
    layer: 3,
    originKey: "request_ip",
    originValue: "10.134.112.38",
    tableType: 0,
  },
  {
    id: 18,
    layer: 3,
    originKey: "rule_version",
    originValue: "v-28-20201231142828",
    tableType: 0,
  },
  {
    id: 19,
    layer: 3,
    originKey: "unit_id",
    originValue: "532",
    tableType: 0,
  },
  {
    id: 20,
    layer: 2,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 21,
    layer: 2,
    originKey: "cost_time",
    originValue: "209 ms",
    tableType: 0,
  },
  {
    id: 22,
    layer: 2,
    originKey: "OBJECT_FIELD_extra_info",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 23,
    layer: 3,
    originKey: "ARRAY_FIELD_cost_time_detail",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 24,
    layer: 4,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 25,
    layer: 5,
    originKey: "OBJECT_FIELD_cost_time_chain",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 26,
    layer: 6,
    originKey: "get_decision_resources_and_init_decision_params",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 27,
    layer: 6,
    originKey: "get_params_for_data_sources_and_compute_features",
    originValue: "4",
    tableType: 0,
  },
  {
    id: 28,
    layer: 6,
    originKey: "access_data_sources_and_compute_features",
    originValue: "50",
    tableType: 0,
  },
  {
    id: 29,
    layer: 6,
    originKey: "analyze_features_and_data_sources_information",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 30,
    layer: 6,
    originKey: "calculate_rules",
    originValue: "3",
    tableType: 0,
  },
  {
    id: 31,
    layer: 6,
    originKey: "total_cost_time_of_this_lev",
    originValue: "57",
    tableType: 0,
  },
  {
    id: 32,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 33,
    layer: 5,
    originKey: "OBJECT_FIELD_data_source_cost_time",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 34,
    layer: 6,
    originKey: "model_20200930_MOB3_nodepen.js",
    originValue: "11",
    tableType: 0,
  },
  {
    id: 35,
    layer: 6,
    originKey: "model_20200930_MOB3WITH_RUNNING_nodepen.js",
    originValue: "17",
    tableType: 0,
  },
  {
    id: 36,
    layer: 6,
    originKey: "model_20200930_MOB1WITH_RUNNING_nodepen.js",
    originValue: "15",
    tableType: 0,
  },
  {
    id: 37,
    layer: 6,
    originKey: "model_20200930_MOB1_nodepen.js",
    originValue: "11",
    tableType: 0,
  },
  {
    id: 38,
    layer: 6,
    originKey: "data_source_total_cost_time",
    originValue: "29",
    tableType: 0,
  },
  {
    id: 39,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 40,
    layer: 5,
    originKey: "OBJECT_FIELD_rule_set_feature_cost_time",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 41,
    layer: 6,
    originKey: "109577",
    originValue: "2",
    tableType: 0,
  },
  {
    id: 42,
    layer: 6,
    originKey: "109608",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 43,
    layer: 6,
    originKey: "feature_total_cost_time",
    originValue: "6",
    tableType: 0,
  },
  {
    id: 44,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 45,
    layer: 5,
    originKey: "OBJECT_FIELD_rule_set_rule_cost_time",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 46,
    layer: 6,
    originKey: "109608",
    originValue: "3",
    tableType: 0,
  },
  {
    id: 47,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 48,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 49,
    layer: 4,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 50,
    layer: 5,
    originKey: "OBJECT_FIELD_cost_time_chain",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 51,
    layer: 6,
    originKey: "get_params_for_data_sources_and_compute_features",
    originValue: "2",
    tableType: 0,
  },
  {
    id: 52,
    layer: 6,
    originKey: "access_data_sources_and_compute_features",
    originValue: "127",
    tableType: 0,
  },
  {
    id: 53,
    layer: 6,
    originKey: "analyze_features_and_data_sources_information",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 54,
    layer: 6,
    originKey: "calculate_rules",
    originValue: "18",
    tableType: 0,
  },
  {
    id: 55,
    layer: 6,
    originKey: "total_cost_time_of_this_lev",
    originValue: "147",
    tableType: 0,
  },
  {
    id: 56,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 57,
    layer: 5,
    originKey: "OBJECT_FIELD_data_source_cost_time",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 58,
    layer: 6,
    originKey: "daichangheimingdan.js",
    originValue: "19",
    tableType: 0,
  },
  {
    id: 59,
    layer: 6,
    originKey: "kg_blacklist.js",
    originValue: "16",
    tableType: 0,
  },
  {
    id: 60,
    layer: 6,
    originKey: "xintianchuangxingyao_xiaodai.js",
    originValue: "25",
    tableType: 0,
  },
  {
    id: 61,
    layer: 6,
    originKey: "kg_account_query.js",
    originValue: "26",
    tableType: 0,
  },
  {
    id: 62,
    layer: 6,
    originKey: "data_source_total_cost_time",
    originValue: "80",
    tableType: 0,
  },
  {
    id: 63,
    layer: 6,
    originKey: "tcredit_starshinePro.js",
    originValue: "21",
    tableType: 0,
  },
  {
    id: 64,
    layer: 6,
    originKey: "tencent_multiloan.js",
    originValue: "24",
    tableType: 0,
  },
  {
    id: 65,
    layer: 6,
    originKey: "tengxuntianyu_xiaodai.js",
    originValue: "21",
    tableType: 0,
  },
  {
    id: 66,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 67,
    layer: 5,
    originKey: "OBJECT_FIELD_rule_set_feature_cost_time",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 68,
    layer: 6,
    originKey: "109488",
    originValue: "10",
    tableType: 0,
  },
  {
    id: 69,
    layer: 6,
    originKey: "109589",
    originValue: "9",
    tableType: 0,
  },
  {
    id: 70,
    layer: 6,
    originKey: "109604",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 71,
    layer: 6,
    originKey: "109622",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 72,
    layer: 6,
    originKey: "109627",
    originValue: "2",
    tableType: 0,
  },
  {
    id: 73,
    layer: 6,
    originKey: "109657",
    originValue: "3",
    tableType: 0,
  },
  {
    id: 74,
    layer: 6,
    originKey: "feature_total_cost_time",
    originValue: "31",
    tableType: 0,
  },
  {
    id: 75,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 76,
    layer: 5,
    originKey: "OBJECT_FIELD_rule_set_rule_cost_time",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 77,
    layer: 6,
    originKey: "109488",
    originValue: "3",
    tableType: 0,
  },
  {
    id: 78,
    layer: 6,
    originKey: "109589",
    originValue: "2",
    tableType: 0,
  },
  {
    id: 79,
    layer: 6,
    originKey: "109604",
    originValue: "2",
    tableType: 0,
  },
  {
    id: 80,
    layer: 6,
    originKey: "109622",
    originValue: "2",
    tableType: 0,
  },
  {
    id: 81,
    layer: 6,
    originKey: "109627",
    originValue: "3",
    tableType: 0,
  },
  {
    id: 82,
    layer: 6,
    originKey: "109657",
    originValue: "5",
    tableType: 0,
  },
  {
    id: 83,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 84,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 85,
    layer: 4,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 86,
    layer: 5,
    originKey: "OBJECT_FIELD_cost_time_chain",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 87,
    layer: 6,
    originKey: "calculate_rules",
    originValue: "2",
    tableType: 0,
  },
  {
    id: 88,
    layer: 6,
    originKey: "total_cost_time_of_this_lev",
    originValue: "2",
    tableType: 0,
  },
  {
    id: 89,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 90,
    layer: 5,
    originKey: "OBJECT_FIELD_rule_set_rule_cost_time",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 91,
    layer: 6,
    originKey: "109577",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 92,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 93,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 94,
    layer: 3,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 95,
    layer: 3,
    originKey: "ARRAY_FIELD_data_source_log",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 96,
    layer: 4,
    originKey: "array_value",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 97,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 98,
    layer: 6,
    originKey: "apiUrl",
    originValue: "http://yxd-risk-model.yxd-risk.paas.idc",
    tableType: 0,
  },
  {
    id: 99,
    layer: 6,
    originKey: "bizId",
    originValue: "28",
    tableType: 0,
  },
  {
    id: 100,
    layer: 6,
    originKey: "costTime",
    originValue: "11",
    tableType: 0,
  },
  {
    id: 101,
    layer: 6,
    originKey: "isSuccess",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 102,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 103,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 104,
    layer: 6,
    originKey: "apiUrl",
    originValue: "http://yxd-risk-model.yxd-risk.paas.idc",
    tableType: 0,
  },
  {
    id: 105,
    layer: 6,
    originKey: "bizId",
    originValue: "28",
    tableType: 0,
  },
  {
    id: 106,
    layer: 6,
    originKey: "costTime",
    originValue: "17",
    tableType: 0,
  },
  {
    id: 107,
    layer: 6,
    originKey: "isSuccess",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 108,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 109,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 110,
    layer: 6,
    originKey: "apiUrl",
    originValue: "http://yxd-risk-model.yxd-risk.paas.idc",
    tableType: 0,
  },
  {
    id: 111,
    layer: 6,
    originKey: "bizId",
    originValue: "28",
    tableType: 0,
  },
  {
    id: 112,
    layer: 6,
    originKey: "costTime",
    originValue: "15",
    tableType: 0,
  },
  {
    id: 113,
    layer: 6,
    originKey: "isSuccess",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 114,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 115,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 116,
    layer: 6,
    originKey: "apiUrl",
    originValue: "http://yxd-risk-model.yxd-risk.paas.idc",
    tableType: 0,
  },
  {
    id: 117,
    layer: 6,
    originKey: "bizId",
    originValue: "28",
    tableType: 0,
  },
  {
    id: 118,
    layer: 6,
    originKey: "costTime",
    originValue: "11",
    tableType: 0,
  },
  {
    id: 119,
    layer: 6,
    originKey: "isSuccess",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 120,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 121,
    layer: 5,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 122,
    layer: 4,
    originKey: "array_value",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 123,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 124,
    layer: 6,
    originKey: "apiUrl",
    originValue: "http://microcredit.jhjj.paas.idc/api/v1/debt/black/detail?",
    tableType: 0,
  },
  {
    id: 125,
    layer: 6,
    originKey: "bizId",
    originValue: "28",
    tableType: 0,
  },
  {
    id: 126,
    layer: 6,
    originKey: "costTime",
    originValue: "19",
    tableType: 0,
  },
  {
    id: 127,
    layer: 6,
    originKey: "isSuccess",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 128,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 129,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 130,
    layer: 6,
    originKey: "apiUrl",
    originValue: "blacklist",
    tableType: 0,
  },
  {
    id: 131,
    layer: 6,
    originKey: "bizId",
    originValue: "28",
    tableType: 0,
  },
  {
    id: 132,
    layer: 6,
    originKey: "costTime",
    originValue: "16",
    tableType: 0,
  },
  {
    id: 133,
    layer: 6,
    originKey: "isSuccess",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 134,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 135,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 136,
    layer: 6,
    originKey: "apiUrl",
    originValue: "http://yxd-risk-feature.yxd-risk.paas.idc",
    tableType: 0,
  },
  {
    id: 137,
    layer: 6,
    originKey: "bizId",
    originValue: "28",
    tableType: 0,
  },
  {
    id: 138,
    layer: 6,
    originKey: "costTime",
    originValue: "25",
    tableType: 0,
  },
  {
    id: 139,
    layer: 6,
    originKey: "isSuccess",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 140,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 141,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 142,
    layer: 6,
    originKey: "apiUrl",
    originValue: "account",
    tableType: 0,
  },
  {
    id: 143,
    layer: 6,
    originKey: "bizId",
    originValue: "28",
    tableType: 0,
  },
  {
    id: 144,
    layer: 6,
    originKey: "costTime",
    originValue: "26",
    tableType: 0,
  },
  {
    id: 145,
    layer: 6,
    originKey: "isSuccess",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 146,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 147,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 148,
    layer: 6,
    originKey: "apiUrl",
    originValue: "tcredit/starshinePro",
    tableType: 0,
  },
  {
    id: 149,
    layer: 6,
    originKey: "bizId",
    originValue: "28",
    tableType: 0,
  },
  {
    id: 150,
    layer: 6,
    originKey: "costTime",
    originValue: "21",
    tableType: 0,
  },
  {
    id: 151,
    layer: 6,
    originKey: "isSuccess",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 152,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 153,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 154,
    layer: 6,
    originKey: "apiUrl",
    originValue: "tencent/multiloan",
    tableType: 0,
  },
  {
    id: 155,
    layer: 6,
    originKey: "bizId",
    originValue: "28",
    tableType: 0,
  },
  {
    id: 156,
    layer: 6,
    originKey: "costTime",
    originValue: "24",
    tableType: 0,
  },
  {
    id: 157,
    layer: 6,
    originKey: "isSuccess",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 158,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 159,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 160,
    layer: 6,
    originKey: "apiUrl",
    originValue: "http://yxd-risk-feature.yxd-risk.paas.idc",
    tableType: 0,
  },
  {
    id: 161,
    layer: 6,
    originKey: "bizId",
    originValue: "28",
    tableType: 0,
  },
  {
    id: 162,
    layer: 6,
    originKey: "costTime",
    originValue: "21",
    tableType: 0,
  },
  {
    id: 163,
    layer: 6,
    originKey: "isSuccess",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 164,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 165,
    layer: 5,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 166,
    layer: 3,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 167,
    layer: 3,
    originKey: "schema_info",
    originValue:
      '[KEY: "" "object has missing required properties ([\\"idType\\"])"] [KEY: "" "object has missing required properties ([\\"applyInfo\\",\\"idType\\"])"] ',
    tableType: 0,
  },
  {
    id: 168,
    layer: 2,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 169,
    layer: 2,
    originKey: "ARRAY_FIELD_fired_rules",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 170,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 171,
    layer: 4,
    originKey: "code",
    originValue: "",
    tableType: 0,
  },
  {
    id: 172,
    layer: 4,
    originKey: "decision",
    originValue: "FORWARD",
    tableType: 0,
  },
  {
    id: 173,
    layer: 4,
    originKey: "decision_addon",
    originValue: "109657,109488,109589,109627,109622,109604",
    tableType: 0,
  },
  {
    id: 174,
    layer: 4,
    originKey: "desc",
    originValue: "小短跳转",
    tableType: 0,
  },
  {
    id: 175,
    layer: 4,
    originKey: "feedback_priority",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 176,
    layer: 4,
    originKey: "note",
    originValue: "",
    tableType: 0,
  },
  {
    id: 177,
    layer: 4,
    originKey: "priority",
    originValue: "50",
    tableType: 0,
  },
  {
    id: 178,
    layer: 4,
    originKey: "probability",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 179,
    layer: 4,
    originKey: "rule_id",
    originValue: "118847",
    tableType: 0,
  },
  {
    id: 180,
    layer: 4,
    originKey: "rule_set_en_name",
    originValue: "better_fouward",
    tableType: 0,
  },
  {
    id: 181,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109608",
    tableType: 0,
  },
  {
    id: 182,
    layer: 4,
    originKey: "ARRAY_FIELD_rule_var_relation",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 183,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 184,
    layer: 4,
    originKey: "status",
    originValue: "online",
    tableType: 0,
  },
  {
    id: 185,
    layer: 4,
    originKey: "ARRAY_FIELD_tag",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 186,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 187,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 188,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 189,
    layer: 4,
    originKey: "code",
    originValue: "",
    tableType: 0,
  },
  {
    id: 190,
    layer: 4,
    originKey: "decision",
    originValue: "DEF_VARS",
    tableType: 0,
  },
  {
    id: 191,
    layer: 4,
    originKey: "decision_addon",
    originValue: "",
    tableType: 0,
  },
  {
    id: 192,
    layer: 4,
    originKey: "desc",
    originValue: "维信金科",
    tableType: 0,
  },
  {
    id: 193,
    layer: 4,
    originKey: "feedback_priority",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 194,
    layer: 4,
    originKey: "note",
    originValue: "",
    tableType: 0,
  },
  {
    id: 195,
    layer: 4,
    originKey: "priority",
    originValue: "50",
    tableType: 0,
  },
  {
    id: 196,
    layer: 4,
    originKey: "probability",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 197,
    layer: 4,
    originKey: "rule_id",
    originValue: "119379",
    tableType: 0,
  },
  {
    id: 198,
    layer: 4,
    originKey: "rule_set_en_name",
    originValue: "channel",
    tableType: 0,
  },
  {
    id: 199,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109657",
    tableType: 0,
  },
  {
    id: 200,
    layer: 4,
    originKey: "ARRAY_FIELD_rule_var_relation",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 201,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 202,
    layer: 6,
    originKey: "created_at",
    originValue: "2020-12-02 19:03:43",
    tableType: 0,
  },
  {
    id: 203,
    layer: 6,
    originKey: "created_user",
    originValue: "shichenglin2",
    tableType: 0,
  },
  {
    id: 204,
    layer: 6,
    originKey: "id",
    originValue: "66543",
    tableType: 0,
  },
  {
    id: 205,
    layer: 6,
    originKey: "rule_id",
    originValue: "119379",
    tableType: 0,
  },
  {
    id: 206,
    layer: 6,
    originKey: "updated_at",
    originValue: "2020-12-02 19:03:43",
    tableType: 0,
  },
  {
    id: 207,
    layer: 6,
    originKey: "updated_user",
    originValue: "shichenglin2",
    tableType: 0,
  },
  {
    id: 208,
    layer: 6,
    originKey: "value",
    originValue: "维信金科",
    tableType: 0,
  },
  {
    id: 209,
    layer: 6,
    originKey: "var_id",
    originValue: "1454",
    tableType: 0,
  },
  {
    id: 210,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 211,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 212,
    layer: 4,
    originKey: "status",
    originValue: "online",
    tableType: 0,
  },
  {
    id: 213,
    layer: 4,
    originKey: "ARRAY_FIELD_tag",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 214,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 215,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 216,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 217,
    layer: 4,
    originKey: "code",
    originValue: "D9999",
    tableType: 0,
  },
  {
    id: 218,
    layer: 4,
    originKey: "decision",
    originValue: "DENY",
    tableType: 0,
  },
  {
    id: 219,
    layer: 4,
    originKey: "decision_addon",
    originValue: "D9999",
    tableType: 0,
  },
  {
    id: 220,
    layer: 4,
    originKey: "desc",
    originValue: "是否命中白户-新天创-天域",
    tableType: 0,
  },
  {
    id: 221,
    layer: 4,
    originKey: "feedback_priority",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 222,
    layer: 4,
    originKey: "note",
    originValue: "",
    tableType: 0,
  },
  {
    id: 223,
    layer: 4,
    originKey: "priority",
    originValue: "50",
    tableType: 0,
  },
  {
    id: 224,
    layer: 4,
    originKey: "probability",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 225,
    layer: 4,
    originKey: "rule_id",
    originValue: "119001",
    tableType: 0,
  },
  {
    id: 226,
    layer: 4,
    originKey: "rule_set_en_name",
    originValue: "baihu_tcredit_tianyu",
    tableType: 0,
  },
  {
    id: 227,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109627",
    tableType: 0,
  },
  {
    id: 228,
    layer: 4,
    originKey: "ARRAY_FIELD_rule_var_relation",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 229,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 230,
    layer: 6,
    originKey: "created_at",
    originValue: "2020-11-20 17:42:04",
    tableType: 0,
  },
  {
    id: 231,
    layer: 6,
    originKey: "created_user",
    originValue: "xiujuanli2",
    tableType: 0,
  },
  {
    id: 232,
    layer: 6,
    originKey: "id",
    originValue: "65636",
    tableType: 0,
  },
  {
    id: 233,
    layer: 6,
    originKey: "rule_id",
    originValue: "119001",
    tableType: 0,
  },
  {
    id: 234,
    layer: 6,
    originKey: "updated_at",
    originValue: "2020-11-20 17:42:04",
    tableType: 0,
  },
  {
    id: 235,
    layer: 6,
    originKey: "updated_user",
    originValue: "xiujuanli2",
    tableType: 0,
  },
  {
    id: 236,
    layer: 6,
    originKey: "value",
    originValue: "$.feature_8294",
    tableType: 0,
  },
  {
    id: 237,
    layer: 6,
    originKey: "var_id",
    originValue: "1303",
    tableType: 0,
  },
  {
    id: 238,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 239,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 240,
    layer: 6,
    originKey: "created_at",
    originValue: "2020-11-20 17:42:04",
    tableType: 0,
  },
  {
    id: 241,
    layer: 6,
    originKey: "created_user",
    originValue: "xiujuanli2",
    tableType: 0,
  },
  {
    id: 242,
    layer: 6,
    originKey: "id",
    originValue: "65637",
    tableType: 0,
  },
  {
    id: 243,
    layer: 6,
    originKey: "rule_id",
    originValue: "119001",
    tableType: 0,
  },
  {
    id: 244,
    layer: 6,
    originKey: "updated_at",
    originValue: "2020-11-20 17:42:04",
    tableType: 0,
  },
  {
    id: 245,
    layer: 6,
    originKey: "updated_user",
    originValue: "xiujuanli2",
    tableType: 0,
  },
  {
    id: 246,
    layer: 6,
    originKey: "value",
    originValue: "D9999",
    tableType: 0,
  },
  {
    id: 247,
    layer: 6,
    originKey: "var_id",
    originValue: "361",
    tableType: 0,
  },
  {
    id: 248,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 249,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 250,
    layer: 4,
    originKey: "status",
    originValue: "online",
    tableType: 0,
  },
  {
    id: 251,
    layer: 4,
    originKey: "ARRAY_FIELD_tag",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 252,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 253,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 254,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 255,
    layer: 4,
    originKey: "code",
    originValue: "",
    tableType: 0,
  },
  {
    id: 256,
    layer: 4,
    originKey: "decision",
    originValue: "DEF_VARS",
    tableType: 0,
  },
  {
    id: 257,
    layer: 4,
    originKey: "decision_addon",
    originValue: "",
    tableType: 0,
  },
  {
    id: 258,
    layer: 4,
    originKey: "desc",
    originValue: "为真返回变量",
    tableType: 0,
  },
  {
    id: 259,
    layer: 4,
    originKey: "feedback_priority",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 260,
    layer: 4,
    originKey: "note",
    originValue: "",
    tableType: 0,
  },
  {
    id: 261,
    layer: 4,
    originKey: "priority",
    originValue: "50",
    tableType: 0,
  },
  {
    id: 262,
    layer: 4,
    originKey: "probability",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 263,
    layer: 4,
    originKey: "rule_id",
    originValue: "119052",
    tableType: 0,
  },
  {
    id: 264,
    layer: 4,
    originKey: "rule_set_en_name",
    originValue: "baihu_tcredit_tianyu",
    tableType: 0,
  },
  {
    id: 265,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109627",
    tableType: 0,
  },
  {
    id: 266,
    layer: 4,
    originKey: "ARRAY_FIELD_rule_var_relation",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 267,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 268,
    layer: 6,
    originKey: "created_at",
    originValue: "2020-11-27 16:10:37",
    tableType: 0,
  },
  {
    id: 269,
    layer: 6,
    originKey: "created_user",
    originValue: "xueyanli3",
    tableType: 0,
  },
  {
    id: 270,
    layer: 6,
    originKey: "id",
    originValue: "65961",
    tableType: 0,
  },
  {
    id: 271,
    layer: 6,
    originKey: "rule_id",
    originValue: "119052",
    tableType: 0,
  },
  {
    id: 272,
    layer: 6,
    originKey: "updated_at",
    originValue: "2020-11-27 16:10:37",
    tableType: 0,
  },
  {
    id: 273,
    layer: 6,
    originKey: "updated_user",
    originValue: "xueyanli3",
    tableType: 0,
  },
  {
    id: 274,
    layer: 6,
    originKey: "value",
    originValue: "未触碰拒贷",
    tableType: 0,
  },
  {
    id: 275,
    layer: 6,
    originKey: "var_id",
    originValue: "361",
    tableType: 0,
  },
  {
    id: 276,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 277,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 278,
    layer: 4,
    originKey: "status",
    originValue: "online",
    tableType: 0,
  },
  {
    id: 279,
    layer: 4,
    originKey: "ARRAY_FIELD_tag",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 280,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 281,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 282,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 283,
    layer: 4,
    originKey: "code",
    originValue: "",
    tableType: 0,
  },
  {
    id: 284,
    layer: 4,
    originKey: "decision",
    originValue: "DEF_VARS",
    tableType: 0,
  },
  {
    id: 285,
    layer: 4,
    originKey: "decision_addon",
    originValue: "",
    tableType: 0,
  },
  {
    id: 286,
    layer: 4,
    originKey: "desc",
    originValue: "非导流渠道-非导流标签",
    tableType: 0,
  },
  {
    id: 287,
    layer: 4,
    originKey: "feedback_priority",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 288,
    layer: 4,
    originKey: "note",
    originValue: "",
    tableType: 0,
  },
  {
    id: 289,
    layer: 4,
    originKey: "priority",
    originValue: "50",
    tableType: 0,
  },
  {
    id: 290,
    layer: 4,
    originKey: "probability",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 291,
    layer: 4,
    originKey: "rule_id",
    originValue: "119414",
    tableType: 0,
  },
  {
    id: 292,
    layer: 4,
    originKey: "rule_set_en_name",
    originValue: "better_fouward_small",
    tableType: 0,
  },
  {
    id: 293,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109604",
    tableType: 0,
  },
  {
    id: 294,
    layer: 4,
    originKey: "ARRAY_FIELD_rule_var_relation",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 295,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 296,
    layer: 6,
    originKey: "created_at",
    originValue: "2020-12-03 17:32:31",
    tableType: 0,
  },
  {
    id: 297,
    layer: 6,
    originKey: "created_user",
    originValue: "xiujuanli2",
    tableType: 0,
  },
  {
    id: 298,
    layer: 6,
    originKey: "id",
    originValue: "66625",
    tableType: 0,
  },
  {
    id: 299,
    layer: 6,
    originKey: "rule_id",
    originValue: "119414",
    tableType: 0,
  },
  {
    id: 300,
    layer: 6,
    originKey: "updated_at",
    originValue: "2020-12-03 17:32:31",
    tableType: 0,
  },
  {
    id: 301,
    layer: 6,
    originKey: "updated_user",
    originValue: "xiujuanli2",
    tableType: 0,
  },
  {
    id: 302,
    layer: 6,
    originKey: "value",
    originValue: "01",
    tableType: 0,
  },
  {
    id: 303,
    layer: 6,
    originKey: "var_id",
    originValue: "1446",
    tableType: 0,
  },
  {
    id: 304,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 305,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 306,
    layer: 4,
    originKey: "status",
    originValue: "online",
    tableType: 0,
  },
  {
    id: 307,
    layer: 4,
    originKey: "ARRAY_FIELD_tag",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 308,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 309,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 310,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 311,
    layer: 4,
    originKey: "code",
    originValue: "000111",
    tableType: 0,
  },
  {
    id: 312,
    layer: 4,
    originKey: "decision",
    originValue: "PASS",
    tableType: 0,
  },
  {
    id: 313,
    layer: 4,
    originKey: "decision_addon",
    originValue: "000111",
    tableType: 0,
  },
  {
    id: 314,
    layer: 4,
    originKey: "desc",
    originValue: "攒新模型",
    tableType: 0,
  },
  {
    id: 315,
    layer: 4,
    originKey: "feedback_priority",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 316,
    layer: 4,
    originKey: "note",
    originValue: "",
    tableType: 0,
  },
  {
    id: 317,
    layer: 4,
    originKey: "priority",
    originValue: "50",
    tableType: 0,
  },
  {
    id: 318,
    layer: 4,
    originKey: "probability",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 319,
    layer: 4,
    originKey: "rule_id",
    originValue: "118436",
    tableType: 0,
  },
  {
    id: 320,
    layer: 4,
    originKey: "rule_set_en_name",
    originValue: "newModelDetil",
    tableType: 0,
  },
  {
    id: 321,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109577",
    tableType: 0,
  },
  {
    id: 322,
    layer: 4,
    originKey: "ARRAY_FIELD_rule_var_relation",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 323,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 324,
    layer: 4,
    originKey: "status",
    originValue: "online",
    tableType: 0,
  },
  {
    id: 325,
    layer: 4,
    originKey: "ARRAY_FIELD_tag",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 326,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 327,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 328,
    layer: 2,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 329,
    layer: 2,
    originKey: "request_url",
    originValue: "/decisionUnit/28/532",
    tableType: 0,
  },
  {
    id: 330,
    layer: 2,
    originKey: "ARRAY_FIELD_skipped_rules",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 331,
    layer: 2,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 332,
    layer: 2,
    originKey: "ARRAY_FIELD_visited_rule_sets",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 333,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 334,
    layer: 4,
    originKey: "OBJECT_FIELD_calculated_vars",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 335,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 336,
    layer: 4,
    originKey: "chosen_rule_id",
    originValue: "118847",
    tableType: 0,
  },
  {
    id: 337,
    layer: 4,
    originKey: "OBJECT_FIELD_cond_vars",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 338,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 339,
    layer: 4,
    originKey: "ARRAY_FIELD_executed_rule_ids",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 340,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 341,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 342,
    layer: 4,
    originKey: "ARRAY_FIELD_fired_rule_ids",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 343,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 344,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 345,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109608",
    tableType: 0,
  },
  {
    id: 346,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 347,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 348,
    layer: 4,
    originKey: "OBJECT_FIELD_calculated_vars",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 349,
    layer: 5,
    originKey: "channel",
    originValue: "维信金科",
    tableType: 0,
  },
  {
    id: 350,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 351,
    layer: 4,
    originKey: "chosen_rule_id",
    originValue: "119379",
    tableType: 0,
  },
  {
    id: 352,
    layer: 4,
    originKey: "OBJECT_FIELD_cond_vars",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 353,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 354,
    layer: 4,
    originKey: "ARRAY_FIELD_executed_rule_ids",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 355,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 356,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 357,
    layer: 4,
    originKey: "ARRAY_FIELD_fired_rule_ids",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 358,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 359,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 360,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109657",
    tableType: 0,
  },
  {
    id: 361,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 362,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 363,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109488",
    tableType: 0,
  },
  {
    id: 364,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 365,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 366,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109589",
    tableType: 0,
  },
  {
    id: 367,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 368,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 369,
    layer: 4,
    originKey: "OBJECT_FIELD_calculated_vars",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 370,
    layer: 5,
    originKey: "denyDate",
    originValue: "2021-02-01",
    tableType: 0,
  },
  {
    id: 371,
    layer: 5,
    originKey: "denyvariable",
    originValue: "D9999",
    tableType: 0,
  },
  {
    id: 372,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 373,
    layer: 4,
    originKey: "chosen_rule_id",
    originValue: "119001",
    tableType: 0,
  },
  {
    id: 374,
    layer: 4,
    originKey: "OBJECT_FIELD_cond_vars",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 375,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 376,
    layer: 4,
    originKey: "ARRAY_FIELD_executed_rule_ids",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 377,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 378,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 379,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 380,
    layer: 4,
    originKey: "ARRAY_FIELD_fired_rule_ids",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 381,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 382,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 383,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 384,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109627",
    tableType: 0,
  },
  {
    id: 385,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 386,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 387,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109622",
    tableType: 0,
  },
  {
    id: 388,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 389,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 390,
    layer: 4,
    originKey: "OBJECT_FIELD_calculated_vars",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 391,
    layer: 5,
    originKey: "guidingType",
    originValue: "01",
    tableType: 0,
  },
  {
    id: 392,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 393,
    layer: 4,
    originKey: "chosen_rule_id",
    originValue: "119414",
    tableType: 0,
  },
  {
    id: 394,
    layer: 4,
    originKey: "OBJECT_FIELD_cond_vars",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 395,
    layer: 5,
    originKey: "denyvariable",
    originValue: "D9999",
    tableType: 0,
  },
  {
    id: 396,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 397,
    layer: 4,
    originKey: "ARRAY_FIELD_executed_rule_ids",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 398,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 399,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 400,
    layer: 4,
    originKey: "ARRAY_FIELD_fired_rule_ids",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 401,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 402,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 403,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109604",
    tableType: 0,
  },
  {
    id: 404,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 405,
    layer: 3,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 406,
    layer: 4,
    originKey: "OBJECT_FIELD_calculated_vars",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 407,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 408,
    layer: 4,
    originKey: "chosen_rule_id",
    originValue: "118436",
    tableType: 0,
  },
  {
    id: 409,
    layer: 4,
    originKey: "OBJECT_FIELD_cond_vars",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 410,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 411,
    layer: 4,
    originKey: "ARRAY_FIELD_executed_rule_ids",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 412,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 413,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 414,
    layer: 4,
    originKey: "ARRAY_FIELD_fired_rule_ids",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 415,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 416,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 417,
    layer: 4,
    originKey: "rule_set_id",
    originValue: "109577",
    tableType: 0,
  },
  {
    id: 418,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 419,
    layer: 2,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 420,
    layer: 1,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 421,
    layer: 1,
    originKey: "message",
    originValue: "normal",
    tableType: 0,
  },
  {
    id: 422,
    layer: 1,
    originKey: "request_id",
    originValue: "c9bd2f19-c2f6-43e7-9cbc-ce9461cd339b",
    tableType: 0,
  },
  {
    id: 423,
    layer: 1,
    originKey: "ARRAY_FIELD_results",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 424,
    layer: 2,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 425,
    layer: 3,
    originKey: "OBJECT_FIELD_decision",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 426,
    layer: 4,
    originKey: "ARRAY_FIELD_fired_rules",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 427,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 428,
    layer: 6,
    originKey: "rule_id",
    originValue: "118847",
    tableType: 0,
  },
  {
    id: 429,
    layer: 6,
    originKey: "note",
    originValue: "",
    tableType: 0,
  },
  {
    id: 430,
    layer: 6,
    originKey: "code",
    originValue: "",
    tableType: 0,
  },
  {
    id: 431,
    layer: 6,
    originKey: "decision",
    originValue: "FORWARD",
    tableType: 0,
  },
  {
    id: 432,
    layer: 6,
    originKey: "rule_set_en_name",
    originValue: "better_fouward",
    tableType: 0,
  },
  {
    id: 433,
    layer: 6,
    originKey: "rule_set_id",
    originValue: "109608",
    tableType: 0,
  },
  {
    id: 434,
    layer: 6,
    originKey: "desc",
    originValue: "小短跳转",
    tableType: 0,
  },
  {
    id: 435,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 436,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 437,
    layer: 6,
    originKey: "rule_id",
    originValue: "119379",
    tableType: 0,
  },
  {
    id: 438,
    layer: 6,
    originKey: "note",
    originValue: "",
    tableType: 0,
  },
  {
    id: 439,
    layer: 6,
    originKey: "code",
    originValue: "",
    tableType: 0,
  },
  {
    id: 440,
    layer: 6,
    originKey: "decision",
    originValue: "DEF_VARS",
    tableType: 0,
  },
  {
    id: 441,
    layer: 6,
    originKey: "rule_set_en_name",
    originValue: "channel",
    tableType: 0,
  },
  {
    id: 442,
    layer: 6,
    originKey: "rule_set_id",
    originValue: "109657",
    tableType: 0,
  },
  {
    id: 443,
    layer: 6,
    originKey: "desc",
    originValue: "维信金科",
    tableType: 0,
  },
  {
    id: 444,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 445,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 446,
    layer: 6,
    originKey: "rule_id",
    originValue: "119001",
    tableType: 0,
  },
  {
    id: 447,
    layer: 6,
    originKey: "note",
    originValue: "",
    tableType: 0,
  },
  {
    id: 448,
    layer: 6,
    originKey: "code",
    originValue: "D9999",
    tableType: 0,
  },
  {
    id: 449,
    layer: 6,
    originKey: "decision",
    originValue: "DENY",
    tableType: 0,
  },
  {
    id: 450,
    layer: 6,
    originKey: "rule_set_en_name",
    originValue: "baihu_tcredit_tianyu",
    tableType: 0,
  },
  {
    id: 451,
    layer: 6,
    originKey: "rule_set_id",
    originValue: "109627",
    tableType: 0,
  },
  {
    id: 452,
    layer: 6,
    originKey: "desc",
    originValue: "是否命中白户-新天创-天域",
    tableType: 0,
  },
  {
    id: 453,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 454,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 455,
    layer: 6,
    originKey: "rule_id",
    originValue: "119052",
    tableType: 0,
  },
  {
    id: 456,
    layer: 6,
    originKey: "note",
    originValue: "",
    tableType: 0,
  },
  {
    id: 457,
    layer: 6,
    originKey: "code",
    originValue: "",
    tableType: 0,
  },
  {
    id: 458,
    layer: 6,
    originKey: "decision",
    originValue: "DEF_VARS",
    tableType: 0,
  },
  {
    id: 459,
    layer: 6,
    originKey: "rule_set_en_name",
    originValue: "baihu_tcredit_tianyu",
    tableType: 0,
  },
  {
    id: 460,
    layer: 6,
    originKey: "rule_set_id",
    originValue: "109627",
    tableType: 0,
  },
  {
    id: 461,
    layer: 6,
    originKey: "desc",
    originValue: "为真返回变量",
    tableType: 0,
  },
  {
    id: 462,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 463,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 464,
    layer: 6,
    originKey: "rule_id",
    originValue: "119414",
    tableType: 0,
  },
  {
    id: 465,
    layer: 6,
    originKey: "note",
    originValue: "",
    tableType: 0,
  },
  {
    id: 466,
    layer: 6,
    originKey: "code",
    originValue: "",
    tableType: 0,
  },
  {
    id: 467,
    layer: 6,
    originKey: "decision",
    originValue: "DEF_VARS",
    tableType: 0,
  },
  {
    id: 468,
    layer: 6,
    originKey: "rule_set_en_name",
    originValue: "better_fouward_small",
    tableType: 0,
  },
  {
    id: 469,
    layer: 6,
    originKey: "rule_set_id",
    originValue: "109604",
    tableType: 0,
  },
  {
    id: 470,
    layer: 6,
    originKey: "desc",
    originValue: "非导流渠道-非导流标签",
    tableType: 0,
  },
  {
    id: 471,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 472,
    layer: 5,
    originKey: "array_value",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 473,
    layer: 6,
    originKey: "rule_id",
    originValue: "118436",
    tableType: 0,
  },
  {
    id: 474,
    layer: 6,
    originKey: "note",
    originValue: "",
    tableType: 0,
  },
  {
    id: 475,
    layer: 6,
    originKey: "code",
    originValue: "000111",
    tableType: 0,
  },
  {
    id: 476,
    layer: 6,
    originKey: "decision",
    originValue: "PASS",
    tableType: 0,
  },
  {
    id: 477,
    layer: 6,
    originKey: "rule_set_en_name",
    originValue: "newModelDetil",
    tableType: 0,
  },
  {
    id: 478,
    layer: 6,
    originKey: "rule_set_id",
    originValue: "109577",
    tableType: 0,
  },
  {
    id: 479,
    layer: 6,
    originKey: "desc",
    originValue: "攒新模型",
    tableType: 0,
  },
  {
    id: 480,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 481,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 482,
    layer: 4,
    originKey: "ARRAY_FIELD_reason",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 483,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 484,
    layer: 5,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 485,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 486,
    layer: 4,
    originKey: "OBJECT_FIELD_variables",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 487,
    layer: 5,
    originKey: "guidingType",
    originValue: "01",
    tableType: 0,
  },
  {
    id: 488,
    layer: 5,
    originKey: "denyDate",
    originValue: "2021-02-01",
    tableType: 0,
  },
  {
    id: 489,
    layer: 5,
    originKey: "denyvariable",
    originValue: "D9999",
    tableType: 0,
  },
  {
    id: 490,
    layer: 5,
    originKey: "ARRAY_FIELD_channel",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 491,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 492,
    layer: 5,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 493,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 494,
    layer: 4,
    originKey: "decision",
    originValue: "DENY",
    tableType: 0,
  },
  {
    id: 495,
    layer: 4,
    originKey: "human_confirm",
    originValue: "",
    tableType: 0,
  },
  {
    id: 496,
    layer: 4,
    originKey: "OBJECT_FIELD_tag_dict",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 497,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 498,
    layer: 4,
    originKey: "status",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 499,
    layer: 4,
    originKey: "ARRAY_FIELD_tags",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 500,
    layer: 4,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 501,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 502,
    layer: 3,
    originKey: "OBJECT_FIELD_features",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 503,
    layer: 4,
    originKey: "max_overdue_days_mil_qy",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 504,
    layer: 4,
    originKey: "xiaomi_userTag",
    originValue: "",
    tableType: 0,
  },
  {
    id: 505,
    layer: 4,
    originKey: "jhjj_overdue_cur_days_qy",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 506,
    layer: 4,
    originKey: "dup_self_ce_applying_cnt_qy",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 507,
    layer: 4,
    originKey: "isInDLapplyChannel",
    originValue: "false",
    tableType: 0,
  },
  {
    id: 508,
    layer: 4,
    originKey: "attackScore",
    originValue: "9999",
    tableType: 0,
  },
  {
    id: 509,
    layer: 4,
    originKey: "amount_date7",
    originValue: "2021-01-09",
    tableType: 0,
  },
  {
    id: 510,
    layer: 4,
    originKey: "denyDate",
    originValue: "2021-02-01",
    tableType: 0,
  },
  {
    id: 511,
    layer: 4,
    originKey: "yxh_age",
    originValue: "29",
    tableType: 0,
  },
  {
    id: 512,
    layer: 4,
    originKey: "OBJECT_FIELD_model20200930MOB1WITHRUNNINGN",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 513,
    layer: 5,
    originKey: "cal_key",
    originValue: "M_THIRDMODEL_20200930_MOB1_WITH_RUNNING|default|3",
    tableType: 0,
  },
  {
    id: 514,
    layer: 5,
    originKey: "is_cal_execute",
    originValue: "True",
    tableType: 0,
  },
  {
    id: 515,
    layer: 5,
    originKey: "OBJECT_FIELD_extra_data",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 516,
    layer: 6,
    originKey: "baihang_mob1",
    originValue: "0.9758639",
    tableType: 0,
  },
  {
    id: 517,
    layer: 6,
    originKey: "xintianchuang_s_mob1",
    originValue: "0.951112",
    tableType: 0,
  },
  {
    id: 518,
    layer: 6,
    originKey: "tanzhi_mob1",
    originValue: "0.9619163",
    tableType: 0,
  },
  {
    id: 519,
    layer: 6,
    originKey: "ylzc_mob1",
    originValue: "0.9494392",
    tableType: 0,
  },
  {
    id: 520,
    layer: 6,
    originKey: "xinyanbehavior_mob1",
    originValue: "0.9302712",
    tableType: 0,
  },
  {
    id: 521,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 522,
    layer: 5,
    originKey: "prediction",
    originValue: "0.1166059631551879",
    tableType: 0,
  },
  {
    id: 523,
    layer: 5,
    originKey: "ARRAY_FIELD_messages",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 524,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 525,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 526,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 527,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 528,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 529,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 530,
    layer: 5,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 531,
    layer: 5,
    originKey: "raw_score",
    originValue: "0.1",
    tableType: 0,
  },
  {
    id: 532,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 533,
    layer: 4,
    originKey: "dup_self_ce_repaying_normal_cnt",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 534,
    layer: 4,
    originKey: "dup_self_ce_overdue_sum_days_qy",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 535,
    layer: 4,
    originKey: "liveGrade",
    originValue: "-1",
    tableType: 0,
  },
  {
    id: 536,
    layer: 4,
    originKey: "livingScore",
    originValue: "9999",
    tableType: 0,
  },
  {
    id: 537,
    layer: 4,
    originKey: "utmSource",
    originValue: "weixinjinkeapiyiye",
    tableType: 0,
  },
  {
    id: 538,
    layer: 4,
    originKey: "attackResult",
    originValue: "true",
    tableType: 0,
  },
  {
    id: 539,
    layer: 4,
    originKey: "XiaoMiFaceCmpScore",
    originValue: "-1",
    tableType: 0,
  },
  {
    id: 540,
    layer: 4,
    originKey: "max_overdueday_other_his",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 541,
    layer: 4,
    originKey: "MoZhiFaceCmpScore",
    originValue: "-1",
    tableType: 0,
  },
  {
    id: 542,
    layer: 4,
    originKey: "other_jhjj_prod_executing_qy2",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 543,
    layer: 4,
    originKey: "isguihurefused",
    originValue: "false",
    tableType: 0,
  },
  {
    id: 544,
    layer: 4,
    originKey: "quality",
    originValue: "abc",
    tableType: 0,
  },
  {
    id: 545,
    layer: 4,
    originKey: "isInyiyepplyChannel",
    originValue: "false",
    tableType: 0,
  },
  {
    id: 546,
    layer: 4,
    originKey: "isInDebtBlacklist",
    originValue: "false",
    tableType: 0,
  },
  {
    id: 547,
    layer: 4,
    originKey: "isInweiboH5applyChannel",
    originValue: "false",
    tableType: 0,
  },
  {
    id: 548,
    layer: 4,
    originKey: "isHasRefuseCode",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 549,
    layer: 4,
    originKey: "dup_self_ce_repaying_overdue_cnt",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 550,
    layer: 4,
    originKey: "blaklist_hit_total_qy",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 551,
    layer: 4,
    originKey: "result_code",
    originValue: "1000",
    tableType: 0,
  },
  {
    id: 552,
    layer: 4,
    originKey: "oneE4",
    originValue: "9999",
    tableType: 0,
  },
  {
    id: 553,
    layer: 4,
    originKey: "trueConstant",
    originValue: "true",
    tableType: 0,
  },
  {
    id: 554,
    layer: 4,
    originKey: "OBJECT_FIELD_model_20200930_MOB3",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 555,
    layer: 5,
    originKey: "cal_key",
    originValue: "M_THIRDMODEL_20200930_MOB3_WITH_RUNNING|default|3",
    tableType: 0,
  },
  {
    id: 556,
    layer: 5,
    originKey: "is_cal_execute",
    originValue: "True",
    tableType: 0,
  },
  {
    id: 557,
    layer: 5,
    originKey: "OBJECT_FIELD_extra_data",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 558,
    layer: 6,
    originKey: "baihang_mob3",
    originValue: "0.8408243",
    tableType: 0,
  },
  {
    id: 559,
    layer: 6,
    originKey: "tanzhi_mob3",
    originValue: "0.9260327",
    tableType: 0,
  },
  {
    id: 560,
    layer: 6,
    originKey: "xinyanbehavior_mob3",
    originValue: "0.8065277",
    tableType: 0,
  },
  {
    id: 561,
    layer: 6,
    originKey: "ylzc_mob3",
    originValue: "0.82883275",
    tableType: 0,
  },
  {
    id: 562,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 563,
    layer: 5,
    originKey: "prediction",
    originValue: "0.12808495475400403",
    tableType: 0,
  },
  {
    id: 564,
    layer: 5,
    originKey: "ARRAY_FIELD_messages",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 565,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 566,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 567,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 568,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 569,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 570,
    layer: 5,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 571,
    layer: 5,
    originKey: "raw_score",
    originValue: "0.1",
    tableType: 0,
  },
  {
    id: 572,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 573,
    layer: 4,
    originKey: "apply_idNumber",
    originValue: "410728199105133056",
    tableType: 0,
  },
  {
    id: 574,
    layer: 4,
    originKey: "baihu_rule_tcredit_tianyu_1",
    originValue: "1",
    tableType: 0,
  },
  {
    id: 575,
    layer: 4,
    originKey: "isFaceSearched",
    originValue: "false",
    tableType: 0,
  },
  {
    id: 576,
    layer: 4,
    originKey: "attackThreshold",
    originValue: "9999",
    tableType: 0,
  },
  {
    id: 577,
    layer: 4,
    originKey: "OBJECT_FIELD_model_20200930_MOB1_nodepen",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 578,
    layer: 5,
    originKey: "cal_key",
    originValue: "M_THIRDMODEL_20200930_MOB1|default|3",
    tableType: 0,
  },
  {
    id: 579,
    layer: 5,
    originKey: "is_cal_execute",
    originValue: "True",
    tableType: 0,
  },
  {
    id: 580,
    layer: 5,
    originKey: "OBJECT_FIELD_extra_data",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 581,
    layer: 6,
    originKey: "xintianchuang_s_mob1",
    originValue: "0.951112",
    tableType: 0,
  },
  {
    id: 582,
    layer: 6,
    originKey: "tongdun_mob1",
    originValue: "0.9146807",
    tableType: 0,
  },
  {
    id: 583,
    layer: 6,
    originKey: "tanzhi_mob1",
    originValue: "0.9619163",
    tableType: 0,
  },
  {
    id: 584,
    layer: 6,
    originKey: "ylzc_mob1",
    originValue: "0.9494392",
    tableType: 0,
  },
  {
    id: 585,
    layer: 6,
    originKey: "xinyanbehavior_mob1",
    originValue: "0.9302712",
    tableType: 0,
  },
  {
    id: 586,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 587,
    layer: 5,
    originKey: "prediction",
    originValue: "0.1374491485295486",
    tableType: 0,
  },
  {
    id: 588,
    layer: 5,
    originKey: "ARRAY_FIELD_messages",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 589,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 590,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 591,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 592,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 593,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 594,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 595,
    layer: 5,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 596,
    layer: 5,
    originKey: "raw_score",
    originValue: "0.1",
    tableType: 0,
  },
  {
    id: 597,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 598,
    layer: 4,
    originKey: "ce_overdue_cur_days_qy",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 599,
    layer: 4,
    originKey: "ce_hist_overdue_max_days_qy",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 600,
    layer: 4,
    originKey: "repaying_amt_without_wecash_qy",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 601,
    layer: 4,
    originKey: "OBJECT_FIELD_model_20200930_MOB3_nodepen",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 602,
    layer: 5,
    originKey: "cal_key",
    originValue: "M_THIRDMODEL_20200930_MOB3|default|3",
    tableType: 0,
  },
  {
    id: 603,
    layer: 5,
    originKey: "is_cal_execute",
    originValue: "True",
    tableType: 0,
  },
  {
    id: 604,
    layer: 5,
    originKey: "OBJECT_FIELD_extra_data",
    originValue: "{",
    tableType: 1,
  },
  {
    id: 605,
    layer: 6,
    originKey: "tanzhi_mob3",
    originValue: "0.9260327",
    tableType: 0,
  },
  {
    id: 606,
    layer: 6,
    originKey: "xinyanbehavior_mob3",
    originValue: "0.8065277",
    tableType: 0,
  },
  {
    id: 607,
    layer: 6,
    originKey: "ylzc_mob3",
    originValue: "0.82883275",
    tableType: 0,
  },
  {
    id: 608,
    layer: 5,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 609,
    layer: 5,
    originKey: "prediction",
    originValue: "0.13286460448281054",
    tableType: 0,
  },
  {
    id: 610,
    layer: 5,
    originKey: "ARRAY_FIELD_messages",
    originValue: "[",
    tableType: 1,
  },
  {
    id: 611,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 612,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 613,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 614,
    layer: 6,
    originKey: "array_value",
    originValue: "",
    tableType: 0,
  },
  {
    id: 615,
    layer: 5,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 616,
    layer: 5,
    originKey: "raw_score",
    originValue: "0.1",
    tableType: 0,
  },
  {
    id: 617,
    layer: 4,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 618,
    layer: 4,
    originKey: "jhjj_hist_cur_overdue_maxdays_qy",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 619,
    layer: 4,
    originKey: "amount_in",
    originValue: "-9999",
    tableType: 0,
  },
  {
    id: 620,
    layer: 4,
    originKey: "isTencentFaceSearched",
    originValue: "false",
    tableType: 0,
  },
  {
    id: 621,
    layer: 4,
    originKey: "IdCardIsForbiddenArea",
    originValue: "false",
    tableType: 0,
  },
  {
    id: 622,
    layer: 4,
    originKey: "oppoFaceResult",
    originValue: "false",
    tableType: 0,
  },
  {
    id: 623,
    layer: 4,
    originKey: "confidence",
    originValue: "9999",
    tableType: 0,
  },
  {
    id: 624,
    layer: 4,
    originKey: "dataSourceTypeMark",
    originValue: "4",
    tableType: 0,
  },
  {
    id: 625,
    layer: 4,
    originKey: "ID_random1_100",
    originValue: "51",
    tableType: 0,
  },
  {
    id: 626,
    layer: 4,
    originKey: "isInyxhH5applyChannel",
    originValue: "false",
    tableType: 0,
  },
  {
    id: 627,
    layer: 4,
    originKey: "isIntoufangapplyChannel",
    originValue: "false",
    tableType: 0,
  },
  {
    id: 628,
    layer: 4,
    originKey: "tencentScore",
    originValue: "-1",
    tableType: 0,
  },
  {
    id: 629,
    layer: 3,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 630,
    layer: 2,
    originKey: "",
    originValue: "}",
    tableType: 2,
  },
  {
    id: 631,
    layer: 1,
    originKey: "",
    originValue: "]",
    tableType: 2,
  },
  {
    id: 632,
    layer: 1,
    originKey: "status",
    originValue: "0",
    tableType: 0,
  },
  {
    id: 633,
    layer: 1,
    originKey: "uav_message",
    originValue:
      "宜享花业务|谛听规则引擎|谛听|rulengine.list@creditease.cn|normal",
    tableType: 0,
  },
];

export default data;
